 cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
(anonymous) @ (index):64
 Download the React DevTools for a better development experience: https://react.dev/link/react-devtools
 Initializing Supabase client with URL: https://dlesebbmlrewsbmqvuza.supabase.co
 Supabase client initialized successfully
 Rendering loading screen... Object
 Rendering loading screen... Object
 Starting auth initialization...
 Auth initialization complete, waiting for auth state...
 Starting auth initialization...
 Auth initialization complete, waiting for auth state...
 Auth initialization complete
 Auth state changed: SIGNED_IN pooja.awandkar22@pccoepune.org
 Setting basic user from session and stopping loading
 Fetching full profile after sign-in...
 Fetching data for authenticated user...
 Network status: Object
 Fetching startups for current user...
 Fetching new investments...
 Fetching startup addition requests...
 Fetching all users...
 Fetching verification requests...
 Fetching all investment offers...
 Auth state changed: INITIAL_SESSION pooja.awandkar22@pccoepune.org
 Setting basic user from session and stopping loading
 Fetching full profile after sign-in...
 Fetching data for authenticated user...
 Network status: Object
 Fetching startups for current user...
 Fetching new investments...
 Fetching startup addition requests...
 Fetching all users...
 Fetching verification requests...
 Fetching all investment offers...
 Found user in Supabase auth: pooja.awandkar22@pccoepune.org
 Found user in Supabase auth: pooja.awandkar22@pccoepune.org
 Found user profile: pooja.awandkar22@pccoepune.org
 Profile data: Object
 Startup name from profile: null
 Profile keys: Array(10)
 Profile startup_name type: object
 Full profile loaded. Updating currentUser with startup_name: null
 Fetching data for authenticated user...
 Network status: Object
 Fetching startups for current user...
 Fetching new investments...
 Fetching startup addition requests...
 Fetching all users...
 Fetching verification requests...
 Fetching all investment offers...
 New investments fetched successfully: 0
 Verification requests fetched successfully: 0
 Startups fetched successfully: 0
 Investment offers fetched successfully: 0
 Users fetched successfully: 1
 Startup addition requests fetched successfully: 0
 Data fetched successfully!
 Startups loaded: 0
 Users loaded: 1
 Current user role: Investor
 New investments fetched successfully: 0
 Verification requests fetched successfully: 0
 Investment offers fetched successfully: 0
 Startup addition requests fetched successfully: 0
 Users fetched successfully: 1
 New investments fetched successfully: 0
 Startup addition requests fetched successfully: 0
 Users fetched successfully: 1
 Verification requests fetched successfully: 0
 Investment offers fetched successfully: 0
 Found user profile: pooja.awandkar22@pccoepune.org
 Profile data: Object
 Startup name from profile: null
 Profile keys: Array(10)
 Profile startup_name type: object
 Full profile loaded. Updating currentUser with startup_name: null
 Fetching data for authenticated user...
 Network status: Object
 Fetching startups for current user...
 Fetching new investments...
 Fetching startup addition requests...
 Fetching all users...
 Fetching verification requests...
 Fetching all investment offers...
 Startups fetched successfully: 0
 Data fetched successfully!
 Startups loaded: 0
 Users loaded: 1
 Current user role: Investor
 Startups fetched successfully: 0
 Data fetched successfully!
 Startups loaded: 0
 Users loaded: 1
 Current user role: Investor
 New investments fetched successfully: 0
 Investment offers fetched successfully: 0
 Users fetched successfully: 1
 Verification requests fetched successfully: 0
 Startup addition requests fetched successfully: 0
 Startups fetched successfully: 0
 Data fetched successfully!
 Startups loaded: 0
 Users loaded: 1
 Current user role: Investor
 Auth state changed: SIGNED_IN pooja.awandkar22@pccoepune.org
 Setting basic user from session and stopping loading
 Fetching full profile after sign-in...
 Fetching data for authenticated user...
 Network status: Object
 Fetching startups for current user...
 Fetching new investments...
 Fetching startup addition requests...
 Fetching all users...
 Fetching verification requests...
 Fetching all investment offers...
auth.ts:60 Found user in Supabase auth: pooja.awandkar22@pccoepune.org
database.ts:324 New investments fetched successfully: 0
database.ts:48 Users fetched successfully: 1
auth.ts:80 Found user profile: pooja.awandkar22@pccoepune.org
auth.ts:81 Profile data: Object
auth.ts:82 Startup name from profile: null
auth.ts:83 Profile keys: Array(10)
auth.ts:84 Profile startup_name type: object
App.tsx:220 Full profile loaded. Updating currentUser with startup_name: null
database.ts:70 Startup addition requests fetched successfully: 0
database.ts:419 Investment offers fetched successfully: 0
database.ts:469 Verification requests fetched successfully: 0
App.tsx:286 Fetching data for authenticated user...
App.tsx:287 Network status: Object
database.ts:83 Fetching startups for current user...
database.ts:312 Fetching new investments...
database.ts:58 Fetching startup addition requests...
database.ts:36 Fetching all users...
database.ts:457 Fetching verification requests...
database.ts:404 Fetching all investment offers...
database.ts:106 Startups fetched successfully: 0
App.tsx:328 Data fetched successfully!
App.tsx:329 Startups loaded: 0
App.tsx:330 Users loaded: 1
App.tsx:331 Current user role: Investor
database.ts:48 Users fetched successfully: 1
database.ts:469 Verification requests fetched successfully: 0
database.ts:324 New investments fetched successfully: 0
database.ts:106 Startups fetched successfully: 0
database.ts:70 Startup addition requests fetched successfully: 0
database.ts:419 Investment offers fetched successfully: 0
App.tsx:328 Data fetched successfully!
App.tsx:329 Startups loaded: 0
App.tsx:330 Users loaded: 1
App.tsx:331 Current user role: Investor
App.tsx:128 Auth state changed: SIGNED_IN pooja.awandkar22@pccoepune.org
App.tsx:143 Setting basic user from session and stopping loading
App.tsx:152 Fetching full profile after sign-in...
App.tsx:286 Fetching data for authenticated user...
App.tsx:287 Network status: Object
database.ts:83 Fetching startups for current user...
database.ts:312 Fetching new investments...
database.ts:58 Fetching startup addition requests...
database.ts:36 Fetching all users...
database.ts:457 Fetching verification requests...
database.ts:404 Fetching all investment offers...
auth.ts:60 Found user in Supabase auth: pooja.awandkar22@pccoepune.org
database.ts:70 Startup addition requests fetched successfully: 0
database.ts:324 New investments fetched successfully: 6
auth.ts:80 Found user profile: pooja.awandkar22@pccoepune.org
auth.ts:81 Profile data: Object
auth.ts:82 Startup name from profile: null
auth.ts:83 Profile keys: Array(10)
auth.ts:84 Profile startup_name type: object
App.tsx:220 Full profile loaded. Updating currentUser with startup_name: null
App.tsx:286 Fetching data for authenticated user...
App.tsx:287 Network status: Object
database.ts:83 Fetching startups for current user...
database.ts:312 Fetching new investments...
database.ts:58 Fetching startup addition requests...
database.ts:36 Fetching all users...
database.ts:457 Fetching verification requests...
database.ts:404 Fetching all investment offers...
database.ts:419 Investment offers fetched successfully: 0
database.ts:106 Startups fetched successfully: 0
database.ts:469 Verification requests fetched successfully: 0
database.ts:48 Users fetched successfully: 1
App.tsx:328 Data fetched successfully!
App.tsx:329 Startups loaded: 0
App.tsx:330 Users loaded: 1
App.tsx:331 Current user role: Investor
database.ts:70 Startup addition requests fetched successfully: 0
database.ts:106 Startups fetched successfully: 0
database.ts:48 Users fetched successfully: 1
database.ts:469 Verification requests fetched successfully: 0
database.ts:419 Investment offers fetched successfully: 0
database.ts:324 New investments fetched successfully: 6
App.tsx:328 Data fetched successfully!
App.tsx:329 Startups loaded: 0
App.tsx:330 Users loaded: 1
App.tsx:331 Current user role: Investor
App.tsx:579 Error submitting offer: ReferenceError: supabase is not defined
    at App.tsx:556:34
    at handleOfferSubmit (InvestorView.tsx:135:9)
    at executeDispatch (react-dom_client.js?v=776e5f79:11736:11)
    at runWithFiberInDEV (react-dom_client.js?v=776e5f79:1485:72)
    at processDispatchQueue (react-dom_client.js?v=776e5f79:11772:37)
    at react-dom_client.js?v=776e5f79:12182:11
    at batchedUpdates$1 (react-dom_client.js?v=776e5f79:2628:42)
    at dispatchEventForPluginEventSystem (react-dom_client.js?v=776e5f79:11877:9)
    at dispatchEvent (react-dom_client.js?v=776e5f79:14792:13)
    at dispatchDiscreteEvent (react-dom_client.js?v=776e5f79:14773:62)
(anonymous) @ App.tsx:579
